### ISSUE TITLE
想问下为什么您dockerhub上的镜像大小只有2G

### ISSUE THREAD

**Issue by AsteriskAzurain** [sakoojiang/image-ai#5]
达摩院提供的准备好环境的镜像大小太大了~ 
看您仓库里的两个dockerfile 使用的基础镜像就是达摩院的镜像 但是为什么build出来的镜像只有2.42GB呢?

![image](https://github.com/sakoojiang/image-ai/assets/48214990/81b0c9ce-b8bb-463d-beca-c90559c30be2)

> ❯ docker image ls | grep modelscope                                                                                         
> registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope   ubuntu20.04-py37-torch1.11.0-tf1.15.5-1.4.3   ee95b0c3e9e3   6 months ago   7.16GB
> registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope   ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.6.1   a4a27f35555f     3 months ago   21.2GB

我这边需要modelscope的环境(有gpu) 但是对镜像大小比较敏感 所以想请教您是怎么做到的

**Comment by sakoojiang** [comment]
应该是docker hub显示有问题，上面显示的应该不是实际大小，你真正pull下来估计有10个G。

我建议自己基于ubuntu做一下基础镜像，只安装必要组件，清除安装过程中的缓存和安装包。

肯定modelscope小很多，但是肯定也是几个G级别的，光pytorch 和gpu驱动就非常大了

**Comment by sakoojiang** [comment]
> 达摩院提供的准备好环境的镜像大小太大了~ 看您仓库里的两个dockerfile 使用的基础镜像就是达摩院的镜像 但是为什么build出来的镜像只有2.42GB呢?
> 
> ![image](https://user-images.githubusercontent.com/48214990/270122603-81b0c9ce-b8bb-463d-beca-c90559c30be2.png)
> 
> > ❯ docker image ls | grep modelscope
> > registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope   ubuntu20.04-py37-torch1.11.0-tf1.15.5-1.4.3   ee95b0c3e9e3   6 months ago   7.16GB
> > registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope   ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.6.1   a4a27f35555f     3 months ago   21.2GB
> 
> 我这边需要modelscope的环境(有gpu) 但是对镜像大小比较敏感 所以想请教您是怎么做到的



应该是docker hub显示有问题，上面显示的应该不是实际大小，你真正pull下来估计有10个G。

我建议自己基于ubuntu做一下基础镜像，只安装必要组件，清除安装过程中的缓存和安装包。

肯定modelscope小很多，但是肯定也是几个G级别的，光pytorch 和gpu驱动就非常大了

**Comment by AsteriskAzurain** [comment]
感谢回复~
我这边按您说的尝试了下 只安装modelscope 用同样的dockerfile在自己的本地和gpu机器上构造出来了大小完全不同的镜像orz
我看了下`pip list`的区别 主要就差在了torch上, 就像您说的torch就有几个G了
```bash
# gpu机器
$ docker image ls | grep modelscope
modelscope-ner-base                debian-slim-py38-cuda113-230924   8a28c296a18d        3 minutes ago       13.9GB
# 本机
❯ docker image ls | grep modelscope                            
modelscope-ner-base                latest                 fd896dfded9e   4 minutes ago   2.59GB
```
```dockerfile
FROM python:3.8.18-slim

RUN apt update && apt install -y build-essential

RUN pip install torch==1.11.0 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu112

RUN pip install "modelscope[nlp]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
```
那看起来即使是自己构建镜像也免不了几个G打底了 非常感谢您的帮助!
